version: '3.4'

services:
  reportservice.api:
    image: ${DOCKER_REGISTRY-}reportserviceapi
    build:
      context: .
      dockerfile: src/Services/ReportService/ReportService.Api/Dockerfile


  phonebookservice.api:
    image: ${DOCKER_REGISTRY-}phonebookserviceapi
    build:
      context: .
      dockerfile: src/Services/PhoneBookService/PhoneBookService.Api/Dockerfile

  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:management
    ports:
     - "15672:15672"
     - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  reportservice.consumerbg:
    image: ${DOCKER_REGISTRY-}reportserviceconsumerbg
    build:
      context: .
      dockerfile: src/Services/Consumer/ReportService.ConsumerBg/Dockerfile

volumes:
  rabbitmq:


